export const ADD_GUEST = 'ADD_GUEST';
export const ADD_GUEST_SUCCESS = 'ADD_GUEST_SUCCESS';
export const ADD_GUEST_FAIL = 'ADD_GUEST_FAIL';

export const EDIT_GUEST = 'EDIT_GUEST';
export const EDIT_GUEST_SUCCESS = 'EDIT_GUEST_SUCCESS';
export const EDIT_GUEST_FAIL = 'EDIT_GUEST_FAIL';

export const DELETE_GUEST = 'DELETE_GUEST';
export const DELETE_GUEST_SUCCESS = 'DELETE_GUEST_SUCCESS';
export const DELETE_GUEST_FAIL = 'DELETE_GUEST_FAIL';

export const GET_GUEST = 'GET_GUEST';
export const GET_GUEST_SUCCESS = 'GET_GUEST_SUCCESS';
export const GET_GUEST_FAIL = 'GET_GUEST_FAIL';

export const GET_TOTAL_GUEST = 'GET_TOTAL_GUEST';
export const GET_TOTAL_GUEST_SUCCESS = 'GET_TOTAL_GUEST_SUCCESS';
export const GET_TOTAL_GUEST_FAIL = 'GET_TOTAL_GUEST_FAIL';

export const GET_ALL_GUESTS = 'GET_ALL_GUESTS';
export const GET_ALL_GUESTS_SUCCESS = 'GET_ALL_GUESTS_SUCCESS';
export const GET_ALL_GUESTS_FAIL = 'GET_ALL_GUESTS_FAIL';